### ISSUE TITLE
Sonar not able to connect to Postgres

### ISSUE THREAD

**Issue by theiamdude** [marcelbirkner/docker-ci-tool-stack#29]
So I am setting this up for the second time. The first time it worked like a dream and that was about 4 months ago. it's a bit challenging to get it up and running. Here is the issue I am facing now:
When the Sonar container, it's not able to connect to SonarDB container. I initially had an issue with SonarDB starting as I was getting this error: 

> chmod: changing permissions of ‘/var/lib/postgresql/data’: Permission denied

I fixed the issue by updating the docker-compose.yml file by updating the volume mount section to the following (notice the :z at the end):

```
volumes:
    - /opt/postgres/data:/var/lib/postgresql/data:z
```

So now I am able to start the postgre container but I am still getting connectivity issue: 

> 2016.10.06 05:20:11 INFO  web[o.s.c.p.Database] Create JDBC datasource for jdbc:postgresql://sonardb:5432/sonar
> 2016.10.06 05:20:11 ERROR web[o.a.c.c.C.[.[.[/]] Exception sending context initialized event to listener instance of class org.sonar.server.platform.PlatformServletContextListener
> java.lang.IllegalStateException: Can not connect to database. Please check connectivity and settings (see the properties prefixed by 'sonar.jdbc.').

I noticed then the docker-compose.yml file does not expose port 5432 on postgre container instead it doing so on the sonar container which did not make sense. I updated compose file to the following:

```
sonar:
  build: ./sonar
  ports:
   - "19000:9000"
   #- "5432:5432"
  networks:
    - prodnetwork
  depends_on:
    - sonardb
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
 sonardb:
  ports:
   - "5432:5432"
  networks:
    - prodnetwork
  image: postgres
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar
  volumes:
    - /opt/postgres/data:/var/lib/postgresql/data:z
```

Unfortunately I am still getting the connectivity issue from Sonar container. The only I am thinking about is that the DB is not created in postgres container and thus unable to connect. Should this step be done manually?

Here is the environment I am running this on:
OS: Fedora 24 
Docker:

```
[emc@cloud docker-ci-tool-stack]$ docker version
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-1.10.3-52.git8b7fa4a.fc24.x86_64
 Go version:      go1.6.3
 Git commit:      8b7fa4a/1.10.3
 Built:           
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-1.10.3-52.git8b7fa4a.fc24.x86_64
 Go version:      go1.6.3
 Git commit:      8b7fa4a/1.10.3
 Built:           
 OS/Arch:         linux/amd64
```

Docker Compose:

```
emc@cloud docker-ci-tool-stack]$ docker-compose version
docker-compose version 1.7.1, build 6c29830
docker-py version: 1.8.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j-fips  26 Sep 2016
```

Your help is greatly appreciated.
Cheers,
Mehdi
